name: Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. 빌드 파일 전송 (배포 파일 업로드)
      - name: Copy build files
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: dist/*
          target: /home/ubuntu/muzusi-web/dist/

      # 5. EC2 서버 설정 및 Nginx 재시작
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # 빌드 파일이 준비된 상태에서 서버 설정 및 Nginx 재시작
            sudo systemctl restart nginx
